version: '3'

services:
  
  db: 
    image: mysql:latest
    environment:
      MYSQL_DATABASE: aws_cc
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: passpass
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "./database:/docker-entrypoint-initdb.d"
    ports:
      - 3306:3306
    networks:
      - aws
  
  www:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/var/www/html"
    ports:
      - 80:80
      - 443:443
    networks:
      - aws
  
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - aws

networks:
  aws:
    driver: bridge